.. This (-*- rst -*-) format file contains commonly used link targets and name
   substitutions.  It may be included in many files, therefore it should only
   contain link targets and name substitutions. Try grepping for "^\.\. _" to
   find plausible candidates for this list.

.. NOTE: reST targets are
   __not_case_sensitive__, so only one target definition is needed for:
   nipy, NIPY, Nipy, etc...


.. project

.. _project pypi: https://pypi.org/project/mne-icalabel/
.. _project conda: https://anaconda.org/conda-forge/mne-icalabel
.. _project github: https://github.com/mne-tools/mne-icalabel
.. _project citation: https://github.com/mne-tools/mne-icalabel/blob/main/CITATION.cff
.. _project license: https://github.com/mne-tools/mne-icalabel/blob/main/LICENSE


.. license

.. _MIT license: https://opensource.org/licenses/MIT
.. _BSD license: https://opensource.org/licenses/BSD-3-Clause


.. mne

.. _mne stable: https://mne.tools/stable/index.html
.. _mne install: https://mne.tools/stable/install/index.html
.. _mne installers: https://mne.tools/stable/install/installers.html
