name: publish
on:  # yamllint disable-line rule:truthy
  release:
    types: [published]
  workflow_dispatch:

jobs:
  pypi:
    if: ${{ github.repository == 'mne-tools/mne-icalabel' }}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/mne-icalabel
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v7
      - run: uv build
      - run: uvx twine check --strict dist/*
      - uses: pypa/gh-action-pypi-publish@release/v1
